# Generated by Django 4.2.4 on 2023-09-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Quiz_author',
            field=models.BooleanField(default=False),
        ),
    ]
