# Generated by Django 4.2.4 on 2023-10-01 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizs', '0007_question_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_slug',
            field=models.CharField(default=1, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=200),
        ),
    ]
