# Generated by Django 4.2.4 on 2023-10-01 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0001_initial'),
        ('quizs', '0009_choise'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='choise',
            new_name='choice',
        ),
    ]
