# Generated by Django 4.2.4 on 2023-10-01 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizs', '0010_rename_choise_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='solve_question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizs.question')),
                ('solver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
